### ISSUE TITLE
Resource Harvester Configuration is unusable (broken Load values)

### ISSUE THREAD

**Issue by Krzeszny** [post-kerbin-mining-corporation/SystemHeat#91] opened 2022-01-09 14:38 UTC
As explained on the KSP forums, non-stock drills have broken stats with this addon installed, resulting in very slow drilling speed, proportionately lower energy consumption, but unchanged mass.

- The Load value shown on the drill never changes and the drilling speed is always several times slower than it should be. Despite that, drills slow down even further when all Engineers go on EVA (without any changes it in the Part Action Window during the present test) and also slow down when thermal efficiency _increases_, counter-intuitively (shown in the PAW). 

- Actual ore extraction speed is different from the value shown in the PAW.

Detailed explanation of test results:
https://forum.kerbalspaceprogram.com/index.php?/topic/193909-112x-systemheat-a-replacement-for-the-coreheat-system-october-3/&do=findComment&comment=4031720

**Comment by Krzeszny** [comment] 2022-01-27 19:52
Duplicate of #89 but it's not just that "it might be screwy". It's literaly unusable.

**Comment by byt3c** [comment] 2022-01-31 20:49
Any chance picking that up ? :)

**Comment by ChrisAdderley** [comment] 2022-02-18 04:05
Closing as duplicate of #89

**Closed by ChrisAdderley** 2022-02-18 04:05 UTC
